### ISSUE TITLE
请教一个小的问题：请问PMP层能套在nn.GraphConv外面吗，还是必须从消息传递处进行修改。谢谢！

### ISSUE THREAD

**Issue by guangmingjian** [he-tiantian/PMP-GNNs#1]
尊敬的作者您好，阅读了您的代码和论文感觉非常棒！因为我想把PMP改成PYG实现，但有遇到了一个小问题不是很确定，所以想冒昧请教一下，请问把PMP套在nn.GraphConv外面能实现吗，这样改动就会小一些，还是必须从消息传递处进行修改呀。如果可以这样是可行的，将节省大量的时间。期待您的回复，感谢！

**Comment by he-tiantian** [comment]
感谢您的提问。PMP-GAT的代码借鉴了DGL团队的GAT框架(在代码文件的头部已经说明)。您提到的那部分代码是默认给出的，我们并没有删除，只是将norm设定为“none”(代码第119行)，这样那部分代码就无效了，不会参与PMP-GAT的训练。

另外关于PMP层是否可以套在nn.GraphConv外面：应该能够实现。可以把PMP层内的用于计算message weights的部分直接挪到层外使用。因为我们没有对这种修改方式进行过实验验证，不确定表现会不会和原有设计的PMP层一样(也可能需要一些finetune)。

**Comment by guangmingjian** [comment]
好的，谢谢您的耐心解答。感谢！！
